title: Github Learning Lab tinkering
author: nrebhun
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Putting bots to the test.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
